backend:
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "/images"
collections:
  - name: "stories"
    label: "Histoires"
    label_singular: "Histoire"
    folder: "stories"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Catégorie", name: "category", widget: "select", options: ["Aventure", "Conte de fées", "Légende", "Classique"] }
      - { label: "Âge", name: "age", widget: "string", hint: "ex: 5-8 ans" }
      - { label: "Résumé", name: "excerpt", widget: "text" }
      - { label: "Image de couverture", name: "cover", widget: "image", required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }